### ISSUE TITLE
Add option to pass additional maven options

### ISSUE THREAD

**Issue by djeanprost** [terrestris/maven-semantic-release#16]
It would like to use specific options to maven in order to add settings lik `-X` or `-ntp`.
For the moment, it's not possible.

**Comment by simonseyock** [comment]
If the option would make sense in general, like `-ntp`, it should be add to [maven.js](https://github.com/terrestris/maven-semantic-release/blob/main/src/maven.js).

Other options like `-X` should be enabled via the options object and could then be applied in [maven.js](https://github.com/terrestris/maven-semantic-release/blob/main/src/maven.js). The options would need to get passed in somehow. Similar to the `processAllModules` option.

**Comment by simonseyock** [comment]
I don't like the idea to be able to pass arbitrary options to the command line. But I am open to arguments :)

**Comment by djeanprost** [comment]
> If the option would make sense in general, like `-ntp`, it should be add to [maven.js](https://github.com/terrestris/maven-semantic-release/blob/main/src/maven.js).
> 
> Other options like `-X` should be enabled via the options object and could then be applied in [maven.js](https://github.com/terrestris/maven-semantic-release/blob/main/src/maven.js). The options would need to get passed in somehow. Similar to the `processAllModules` option.

Hello @simonseyock 

For -ntp, I don't see why people wouldn't want to have it hardcoded in the tool because it causes lots of log entries by maven. So maybe the solution is to add it in maven.js indeed.
For others options, I think it's valuable to allow people to use any options maven can handle so a way of doing that should be provided to users of your library.

**Comment by simonseyock** [comment]
I agree about `-ntp`.

The problem that I see, is that we then pass options from some configuration file directly onto the command line. I don't know if that is a huge problem, but I do not know all the implications of that.

**Comment by djeanprost** [comment]
Well, we already discussed this topic on https://github.com/terrestris/maven-semantic-release/issues/17 about the fact that allowing the usage of "any" options on the command line could be a problem. From my point of view I understand the risk, but I don't think the solution is to prevent users to use maven options in your tool. This is why I'm telling that it is the responsability of the CI pipeline maintainer to check that no one uses it badly and to protect variable so that they cannot be read by unauthorized people or whatever.

So my point is still to allow people to use maven option freely 😀
At least if we agree on `-ntp` maybe we can create this change ?

**Comment by simonseyock** [comment]
`-ntp` is added as default and `-X` can be activated via the `debug` option now
