### ISSUE TITLE
Can path checks get removed?

### ISSUE THREAD

**Issue by simonseyock** [terrestris/maven-semantic-release#17]
> I introduced the checks because I was not totally sure that it would be a good idea to allow unsanitized input that will be passed into `exec`. The value comes form a config file, though.
>
> I am not entirely sure, consider this scenario:
> A repository is using this plugin in a pipeline that runs on PR. A user inserts malicious code into the config file that prints out secrets. The pipeline will run with the changed config and the secrets are leaked.
>
> I don't know if I am overly paranoid. Is the scenario realistic? How is this handled in other github actions?
> 
> In the end it would be nice if we could get rid of these checks because it is annoying to maintain them.

_Originally posted by @simonseyock in https://github.com/terrestris/maven-semantic-release/pull/15#discussion_r1205431617_

**Comment by marcjansen** [comment]
Just my 2 cents:

Please check the variables for sanity before passing them through to something which is will result in an executed command. I'd go so far to even check if the file is actually existing.

execa will most likely pass through what it is given and can hardly ever catch cases where someone tries to sneak in a malicious command.

**Comment by hwbllmnn** [comment]
I'd also leave the check in for now. I actually doubt that the issue of the regexp not being sufficient will pop up any time soon again.
