### ISSUE TITLE
create new release with latest bug fixes

### ISSUE THREAD

**Issue by djeanprost** [terrestris/maven-semantic-release#18]
Hello @hwbllmnn 
Would you mind releasing a new version of the plugin including latest bug fixes please ?
#11, #12, #13 
thank you

**Comment by djeanprost** [comment]
Hello @hwbllmnn 
Sorry for tagging you, but I would really appreciate the release of the component 😀

**Comment by simonseyock** [comment]
Sorry for being so slow. I released a new version :see_no_evil:

**Comment by djeanprost** [comment]
Hello @simonseyock who's in charge of publishing the version in npm registry ? https://www.npmjs.com/package/semantic-release-maven

**Comment by simonseyock** [comment]
This plugin is released under https://www.npmjs.com/package/@terrestris/maven-semantic-release
