### ISSUE TITLE
Publish a sample releaserc config file please

### ISSUE THREAD

**Issue by jasondamour** [terrestris/maven-semantic-release#27]
Hello,

Semantic-Release's config format is mess... the most confusing data structure I've ever seen. Do you mind posting a sample configuration in some format (I'm using yaml via a .releaserc.yml) either in this ticket or even better in the readme?

Thank you!

**Comment by jasondamour** [comment]
Here was my guess at configuration format:
```
plugins:
  - - '@terrestris/maven-semantic-release'
    - processAllModules: true
      debug: true
```

**Comment by jasondamour** [comment]
I think I got it right. Follow up question, is it possible to make settingsPath default to the users home directory, i.e. `~/.m2/settings.xml` instead of the cwd.

**Comment by jasondamour** [comment]
How is one supposed to pass tags to the jib build command, if mvn targets are matched against an arbitrary list? I need to set something like 
```
  - - '@terrestris/maven-semantic-release'
    - processAllModules: true
      mavenTarget: package jib:build -Djib.to.tags=${nextRelease.version}

```

**Comment by simonseyock** [comment]
Hello @jasondamour, thanks for your feedback. An example file can be provided, that is no problem.

Regarding the path to the `settings.xml` it would make sense to use home indeed as `action/setup-java` uses this exact path. It would be possible to be able to remove the path. I think normally this action will be used in conjunction with `action/setup-java` so there should exist a `settings.xml`. Will there be a case where no `settings.xml` should be used?

We don't allow passing of arbitrary options directly to the command line. Even if we would, you want to have the next release version passed in. That would need a change in the code anyways.

I don't exactly see how setting `jib.to.tags=${nextRelease.version}` would do anything? Jib should already pushes to the version set in the `pom.xml` or not? And that would be exactly `${nextRelease.version}`. But if needed I can add that to the code.

**Comment by jasondamour** [comment]
Ah, I didn't realize setup-java created a default settings.xml, so I think thats fine then. I was trying to run a dry-run locally to test this new plugin and thats when I had the issue.

No, Jib does not automatically use the version from pom.xml as far as I'm aware, the only default tag is `latest`. And even if I modified my pom.xml to add some additional tags, there is still other information from the build platform I need to pass in to jib, like OS/Arch, build args, and other tags. I want to tag my image with more than just `nextRelease.version`. Honestly, I don't understand why there is a limited list of commands available. What if I need to release only a single submodule, with `mvn -pl <my-project>`? What if I need to change maven output flags beyond simple debug boolean?

**Comment by simonseyock** [comment]
It is possible to configure jib via `pom.xml`. Pushing additional tags can be done for example like this:
```<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>${jib-maven-plugin.version}</version>
  <configuration>
    <to>
      <image>${image}</image>
      <tags>
        <tag>${project.version}</tag>
        <tag>${project.version}-${git.commit.id.abbrev}</tag>
      </tags>
    </to>
  </configuration>
</plugin>
```

I think almost all configuration of jib can be done via the `pom.xml` and in my opinion this normally would be the preferred way over using cli options.

**Comment by simonseyock** [comment]
https://github.com/terrestris/maven-semantic-release/pull/28

**Comment by jasondamour** [comment]
> I think almost all configuration of jib can be done via the `pom.xml` and in my opinion this normally would be the preferred way over using cli options.

IMO its impossible to achieve the level of flexibility provided by CLI options through pom.xml. Outside of SemVer, I am using this [docker metadata action](https://github.com/docker/metadata-action) to generate the list of tags and labels for my images. My regular jib build process looks like this:

```
    - name: Docker Metadata
      id: docker-metadata
      uses: docker/metadata-action
      with:
        sep-tags: ','
        sep-labels: ','
        tags: |
          type=sha,prefix=,suffix=,format=long
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{raw}}
          type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
    - name: Maven Build
      run: >
        mvn 
        package jib:build
        --batch-mode --update-snapshots --no-transfer-progress
        -Djib.to.tags=${{ steps.docker-metadata.outputs.tags }}
        -Djib.container.labels=${{ steps.docker-metadata.outputs.labels }}
```

This job dynamically generates my list of tags based on git events. Without the ability to pass the list of tags to the release job, I'll need to try to replicate this tagging behavior again through pom.xml.

Can you suggest to me a pom.xml configuration which achieves the similar as above:
- Images will always be tagged with long commit sha
- Images from Branch commits will be tagged with `:<branch-name>`
- Images from PRs will be tagged with `:pr-<PR-id>`
- Images from tags will be tagged with:
  - `:<raw-tag>`
  - `:v{{major}}.{{minor}}.{{patch}}`
  - `v{{major}}.{{minor}}`
  - `v{{major}}`

If your plugin supported specifying tags, then my sematic release would simply use the same output tags/labels from the docker-metadata step, and I could maintain my tagging pattern in one central place.

**Comment by simonseyock** [comment]
ok, that might be difficult. I will think about what to do. And also consider best practices.

**Comment by simonseyock** [comment]
I think this is outside the scope of this small open-source plugin. Feel free to start working on this, but be aware that we would want to keep this plugin rather simple so the maintenance will stay low. If there is high demand for a feature like this we could reopen the issue.
