### ISSUE TITLE
Support the maven wrapper

### ISSUE THREAD

**Issue by gdupontf** [terrestris/maven-semantic-release#32]
As it stands this doesn't support the [maven wrapper](https://maven.apache.org/wrapper/).

Either autodetection or a flag for switching the command "binary" would suffice.

**Comment by gdupontf** [comment]
It's a pair of native scripts (mvnw and mvnw.cmd), pretty much always committed alongside the source at the root.

So invoking `mvnw` at repository root with the same arguments as a regular mvn command is all there is to it.

**Comment by simonseyock** [comment]
I created a PR for this. Can you look over it?

I just replaced the command `'mvn'` with `'./mvnw'` if the option `mvnw` is set. Is there a need to support the windows version?
